# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
import grpc

import FederatedML_pb2 as FederatedML__pb2


class FederatedMLStub(object):
    """Missing associated documentation comment in .proto file"""

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.GetModel = channel.unary_unary(
                '/FederatedML/GetModel',
                request_serializer=FederatedML__pb2.Option.SerializeToString,
                response_deserializer=FederatedML__pb2.Model.FromString,
                )
        self.SendModel = channel.unary_unary(
                '/FederatedML/SendModel',
                request_serializer=FederatedML__pb2.Model.SerializeToString,
                response_deserializer=FederatedML__pb2.Empty.FromString,
                )


class FederatedMLServicer(object):
    """Missing associated documentation comment in .proto file"""

    def GetModel(self, request, context):
        """Missing associated documentation comment in .proto file"""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def SendModel(self, request, context):
        """Missing associated documentation comment in .proto file"""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_FederatedMLServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'GetModel': grpc.unary_unary_rpc_method_handler(
                    servicer.GetModel,
                    request_deserializer=FederatedML__pb2.Option.FromString,
                    response_serializer=FederatedML__pb2.Model.SerializeToString,
            ),
            'SendModel': grpc.unary_unary_rpc_method_handler(
                    servicer.SendModel,
                    request_deserializer=FederatedML__pb2.Model.FromString,
                    response_serializer=FederatedML__pb2.Empty.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'FederatedML', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))


 # This class is part of an EXPERIMENTAL API.
class FederatedML(object):
    """Missing associated documentation comment in .proto file"""

    @staticmethod
    def GetModel(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/FederatedML/GetModel',
            FederatedML__pb2.Option.SerializeToString,
            FederatedML__pb2.Model.FromString,
            options, channel_credentials,
            call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def SendModel(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/FederatedML/SendModel',
            FederatedML__pb2.Model.SerializeToString,
            FederatedML__pb2.Empty.FromString,
            options, channel_credentials,
            call_credentials, compression, wait_for_ready, timeout, metadata)
